= XL Docker images for XL Release

This repository contains the source code for two flavors of Docker images for XL release:
* The regular image, which based on the Alpine Linux flavor of the [OpenJDK base image](https://hub.docker.com/_/openjdk/)
* The Red Hat certified image, which is baed on the rhel7-atomic base image



== Building the images

To build the regular image:
[source,shell]
----
$ docker build --build-arg XLR_VERSION=8.1.0 --tag xebialabs/xl-release:v8.1 --tag xebialabs/xl-release:v8.1-alpine --tag xebialabs/xl-release:v8.1.0 --tag xebialabs/xl-release:v8.1.0-alpine -f alpine/Dockerfile .
---

For non-final versions, use:
[source,shell]
----
$ docker build --build-arg XLR_VERSION=8.1.0-rc.2 --tag xebialabs/xl-release:v8.1.0-rc.2 --tag xebialabs/xl-release:v8.1.0-rc.2-alpine -f alpine/Dockerfile .
----

To publish the regular image:
[source,shell]
----
$ docker push xebialabs/xl-release:v8.0
$ docker push xebialabs/xl-release:v8.0-alpine
$ docker push xebialabs/xl-release:v8.0.1
$ docker push xebialabs/xl-release:v8.0.1-alpine
----

To publsh non-final versions, use:
[source,shell]
----
$ docker push xebialabs/xl-release:v8.1.0-rc.2
$ docker push xebialabs/xl-release:v8.1.0-rc.2-alpine
----


To build the Red Hat certified image:
[source,shell]
----
$ docker build --build-arg XLR_VERSION=8.0.1 --tag xebialabs/xl-release:v8.0-rhel --tag xebialabs/xl-release:v8.0.1-rhel -f rhel/Dockerfile buildContext
----
